name: Release

on:
  push:
    branches: [james-se212website]
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2-beta
        with:
          node-version: "18.17"

      - run: npm install

      - run: npm run build

      - run: tar -cJf ../James.tar.gz *
        working-directory: build/

      - run: echo "::set-output name=datetime::$(date +'%Y-%m-%dT%H-%M-%S')"
        id: datetime

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "James.tar.xz"
          tag: ${{ steps.datetime.outputs.datetime }}
          commit: "main-se212website"
          token: ${{ secrets.GITHUB_TOKEN }}
